var EMAIL_RECIPIENTS = ['INSERT_EMAIL_ADDRESSES_HERE'];

function sendEmail (url) {
  var footerStyle = 'color: #aaaaaa; font-style: italic;';
  var scriptwiseLink = 'www.cicerotully.co.uk/scripts'
  var subject = 'AdWords Script Data ' + getDateStringInTimeZone('dd MMM yyyy');
  var htmlBody = '<html><body>' +
      '<p>Hello,</p>' +
      '<p>An AdWords Script has run successfully on your account and the output is available ' +
      '<p>here:' +
      '<ul><li><a href="' + url +
      '">AdWords _______ Script Results</a></li></ul></p>' +
      '<p>Regards,</p>' +
      '<span style="' + footerStyle + '">This email was automatically ' +
      'generated by <a href="' + scriptwiseLink + '"Scriptwise Marketing Scripts</a>.</span>' +
      '<body></html>';
  var body = 'Please enable HTML to view this report.';
  var options = {htmlBody: htmlBody};

  MailApp.sendEmail(EMAIL_RECIPIENTS, subject, body, options);
}
